version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        command: sleep infinity
        user: root
        ports:
            - 5001:5001
        depends_on:
            - minio
        volumes:
            - ..:/workspace:cached

    minio:
        image: quay.io/minio/minio
        ports:
            - 9000:9000
            - 9001:9001
        restart: unless-stopped
